### ISSUE TITLE
/log-deleted serialize pb

### ISSUE THREAD

**Issue by P0SlX** [P0SlX/Atrium#22]
```
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]: node:events:491
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:       throw er; // Unhandled 'error' event
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:       ^
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]: TypeError: Cannot read properties of undefined (reading 'serialize')
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at Object.execute (/home/p0slx/Atrium/events/messageDelete.js:15:12)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at Client.<anonymous> (/home/p0slx/Atrium/index.js:39:50)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at Client.emit (node:events:513:28)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at MessageDeleteAction.handle (/home/p0slx/Atrium/node_modules/discord.js/src/client/actions/MessageDelete.js:24:16)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at module.exports [as MESSAGE_DELETE] (/home/p0slx/Atrium/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_DELETE.js:4:32)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at WebSocketManager.handlePacket (/home/p0slx/Atrium/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at WebSocketShard.onPacket (/home/p0slx/Atrium/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at WebSocketShard.onMessage (/home/p0slx/Atrium/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at callListener (/home/p0slx/Atrium/node_modules/ws/lib/event-target.js:290:14)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at WebSocket.onMessage (/home/p0slx/Atrium/node_modules/ws/lib/event-target.js:209:9)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]: Emitted 'error' event on Client instance at:
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at emitUnhandledRejectionOrErr (node:events:394:10)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]:     at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
Jan 12 10:52:24 ARM-Server start_atrium.sh[3313971]: Node.js v19.2.0
```

**Comment by P0SlX** [comment]
Fix 5245219804f2ed41c38835d0615a0589351a52c4
